### PR TITLE
Add security context constraints and cluster role bindings

### PR DESCRIPTION
**Pull request by simon3z**
This PR adds the support for:
- security context constraint entity
- cluster role binding entity

### CODE REVIEW

**Comment by simon3z** [comment]
cc @abonas

**Comment by abonas** [comment]
@simon3z , how does the retrieval work for security context constraint if it's not available on /oapi, and this gem talks to /oapi ?

**Comment by abonas** [comment]
@simon3z what's the status of this PR? afaik part of it submitted and was merged in #16

**Comment by simon3z** [comment]
> @simon3z what's the status of this PR? afaik part of it submitted and was merged in #16

I'll resume working on this asap. If you're cleaning up the open PR feel free to close it, I'll re-open it when I'll have time. Thanks.

**Pull request closed without merging**
