### PR TITLE
Add support for creating project request

### PR DESCRIPTION
**Pull request by zakiva**
This PR adds support for creating project request in order to allow users to create Self-Provisioned Projects. 
Relevant Openshift docs:
https://docs.openshift.com/enterprise/3.0/admin_guide/selfprovisioned_projects.html

 Need to add tests and update the readme.

### CODE REVIEW

**Comment by zakiva** [comment]
@abonas @simon3z @zeari

**Comment by moolitayer** [comment]
This should be covered by https://github.com/abonas/kubeclient/pull/185
@zakiva Did you manage to create a kubeclient for openshift?

```
client = Kubeclient::Client.new('http://localhost:8443/oapi')
client.create_project_request ...
```

**Comment by zakiva** [comment]
> This should be covered by abonas/kubeclient#185
> @zakiva Did you manage to create a kubeclient for openshift?
> 
> client = Kubeclient::Client.new('http://localhost:8443/oapi')
> client.create_project_request ...

yes, it seems to work for me.

**Comment by zakiva** [comment]
Closing, covered by https://github.com/abonas/kubeclient/pull/185.

**Pull request closed without merging**
